---

- name: Add the Kubeadm/kubernetes repository.
  yum_repository:
    name: kubernetes
    description: Kubernetes and Kubeadm repository.
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    exclude:
      - kube*

- name: Add the GPG key for the Kubernetes repository.
  rpm_key:
    state: present 
    key:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
