---
#From https://github.com/kubernetes/contrib/blob/master/ansible/roles/node/tasks/swapoff.yml

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disabled Firewalld that comes pre-bundled in Centos.
  service: 
    name: firewalld
    state: stopped
    enabled: no

- name: Make sure we allow local switched/routed packets to go through iptables.
  modprobe:
    name: br_netfilter
    state: present

- name: Enable bridge-nf-call-iptables for IPv4.
  sysctl:
    name: net.bridge.bridge-nf-call-iptables 
    value: 1
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf

- name: Enable bridge-nf-call-ip6tables for IPv6.
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables 
    value: 1
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf